### ISSUE TITLE
Doesn't work on Ubuntu 16.04

### ISSUE THREAD

**Issue by codefuhrer** [xflux-gui/xflux-gui#18]
```python
Exception AttributeError: 
AttributeError("'FluxGUI' object has no attribute 'xflux_controller'",) in 
<bound method FluxGUI.__del__ of <__main__.FluxGUI object at 0x7f7fdd9333d0>> ignored
```
Console xflux works fine.

**Comment by ntc2** [comment]
How did you install? Installing from source works for me on 16.04.

**Comment by codefuhrer** [comment]
Installed from PPA.

**Comment by ntc2** [comment]
The version in the PPA is very old. Try installing from source and see if
the problem goes away.

**Comment by codefuhrer** [comment]
Yeah, works fine now. Thanks :+1:

**Comment by ntc2** [comment]
Thanks for testing. I'll see if the guy who maintains the PPA will upload a new version.

**Comment by NHellFire** [comment]
I've uploaded a new version now.

**Comment by AntonioCS** [comment]
@ntc2 I am on ubuntu 16.06 and while it does install, the preview does nothing nor does it change anything when it gets dark
